#!/usr/bin/env python3
"""
MEMORY SYNC AGENT
=====================
Fail-closed. Append-only.
Runs every hour on GCP. Aggregates all agent states into a single
memory.md file. Posts status to Telegram. This is the persistent
brain of the agent network — always current, always searchable.

Deploy: ~/agents/memory_sync/memory_sync.py
Cron:   */60 * * * * cd ~/agents/memory_sync && python3 memory_sync.py
"""

import os
import shlex
import json
import subprocess
import datetime
import requests
import pathlib

APP_HOST = os.getenv("APP_URL", "")

# ── CONFIG ──────────────────────────────────────────────────
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")
GCP_USER = os.getenv("GCP_USER")
MEMORY_FILE = pathlib.Path.home() / "memory.md"
STATE_DIR = pathlib.Path.home() / "agents"
LOG_FILE = pathlib.Path.home() / "agents/memory_sync/sync.log"

# Agent locations and their status files/patterns
AGENTS = {
    "domain_scorer": {
        "path": "~/agents/domain_scorer/",
        "log": "~/agents/domain_scorer/domain_scorer.log",
    },
    "trading_executor": {
        "path": "~/agents/trading_executor/",
        "log": "~/agents/trading_executor/trading_executor.log",
    },
    "task_watchdog": {
        "path": "~/agents/task_watchdog/",
        "log": "~/agents/task_watchdog/task_watchdog.log",
    },
    "signal_parser": {
        "path": "~/agents/signal parser/",
        "log": "~/agents/signal parser/signal parser.log",
    },
    "Verifier": {
        "path": os.path.expanduser(os.getenv("AGENT_HOME", "~/.agent-network") + "/"),
        "log": os.path.expanduser(os.getenv("AGENT_HOME", "~/.agent-network") + "/verifier.log"),
    },
}

# ── UTILS ────────────────────────────────────────────────────
def log(msg):
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line)
    with open(LOG_FILE, "a") as f:
        f.write(line + "\n")

def run_cmd(cmd):
    """Run a fixed internal command. Accepts a string or an argv list; never a shell."""
    argv = shlex.split(cmd) if isinstance(cmd, str) else list(cmd)
    try:
        result = subprocess.run(
            argv, capture_output=True, text=True, timeout=10
        )
        return result.stdout.strip() or result.stderr.strip() or "(no output)"
    except Exception as e:
        return f"ERROR: {e}"

def telegram(msg):
    if not TELEGRAM_TOKEN:
        log("TELEGRAM_TOKEN not set — skipping Telegram")
        return
    try:
        requests.post(
            f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage",
            json={"chat_id": TELEGRAM_CHAT_ID, "text": msg, "parse_mode": "Markdown"},
            timeout=10,
        )
    except Exception as e:
        log(f"Telegram error: {e}")

# ── AGENT STATUS CHECKS ──────────────────────────────────────
# Pipes and globs are done in Python rather than handed to a shell. `ps aux`
# output is data, not a command; filtering it here means a process name can
# never become an injection vector.
def check_process(name_pattern):
    """Check whether a process matching the pattern is running."""
    out = run_cmd(["ps", "aux"])
    if out.startswith("ERROR"):
        return {"alive": False, "pid": None, "snippet": "NOT RUNNING"}
    matches = [
        line for line in out.splitlines()
        if name_pattern in line and "grep" not in line
    ][:3]
    if not matches:
        return {"alive": False, "pid": None, "snippet": "NOT RUNNING"}
    fields = matches[0].split()
    pid = fields[1] if len(fields) > 1 else "?"
    return {"alive": True, "pid": pid, "snippet": "\n".join(matches)[:120]}

def read_log_tail(log_path, lines=15):
    """Read the last N lines of a log file."""
    expanded = pathlib.Path(os.path.expanduser(log_path))
    if not expanded.is_file():
        return "No log found"
    try:
        tail = expanded.read_text(errors="replace").splitlines()[-lines:]
    except OSError:
        return "No log found"
    return "\n".join(tail) or "(empty)"

def get_crontab():
    return run_cmd(["crontab", "-l"])

def get_disk_usage():
    out = run_cmd(["df", "-h", os.path.expanduser("~")])
    lines = out.splitlines()
    return lines[-1] if lines else "(no output)"

def get_uptime():
    return run_cmd(["uptime", "-p"])

# ── BUILD MEMORY FILE ────────────────────────────────────────
def build_memory(agent_states, now):
    """
    Build the memory.md file — the single source of truth
    that Claude reads at the start of every session.
    """
    ts = now.strftime("%Y-%m-%d %H:%M:%S UTC")
    date = now.strftime("%B %d, %Y")

    lines = [
        f"# LIVE STATE",
        f"**Last Updated:** {ts}",
        f"**Generated by:** Memory Sync Agent (auto)",
        f"",
        f"---",
        f"",
        f"## GCP INFRASTRUCTURE",
        f"- **Host:** REDACTED",
        f"- **User:** {GCP_USER}",
        f"- **Uptime:** {get_uptime()}",
        f"- **Disk:** {get_disk_usage()}",
        f"",
        f"## ACTIVE AGENTS",
        f"",
    ]

    for name, state in agent_states.items():
        status = "🟢 ALIVE" if state["process"]["alive"] else "🔴 DEAD"
        pid = state["process"]["pid"] or "—"
        lines += [
            f"### {name}",
            f"- **Status:** {status}",
            f"- **PID:** {pid}",
            f"- **Last log:**",
            f"```",
            state["log_tail"][:400],
            f"```",
            f"",
        ]

    lines += [
        f"## CRONTAB",
        f"```",
        get_crontab(),
        f"```",
        f"",
        f"## SESSION NOTES",
        f"- Memory sync ran: {ts}",
        f"- Next sync: ~1 hour",
        f"- This file is the source of truth for Claude sessions",
        f"- Claude should search this file first in every session",
        f"",
    ]

    return "\n".join(lines)

# ── TELEGRAM REPORT ──────────────────────────────────────────
def build_telegram_report(agent_states, now):
    ts = now.strftime("%m/%d %H:%M")
    alive = [n for n, s in agent_states.items() if s["process"]["alive"]]
    dead  = [n for n, s in agent_states.items() if not s["process"]["alive"]]

    report = [
        f"⚡ *MEMORY SYNC* — {ts}",
        f"",
        f"*AGENTS ALIVE ({len(alive)}/{len(agent_states)})*",
    ]
    for name in alive:
        pid = agent_states[name]["process"]["pid"]
        report.append(f"  🟢 {name} · PID {pid}")
    if dead:
        report.append(f"")
        report.append(f"*AGENTS DOWN*")
        for name in dead:
            report.append(f"  🔴 {name} — NOT RUNNING")

    report += [
        f"",
        f"Memory file updated. Claude is current.",
    ]
    return "\n".join(report)

# ── MAIN ─────────────────────────────────────────────────────
def main():
    now = datetime.datetime.utcnow()
    log("=" * 50)
    log("the agent network Memory Sync starting")

    agent_states = {}
    process_patterns = {
        "domain_scorer": "domain_scorer.py",
        "trading_executor": "trading_executor",
        "task_watchdog": "task_watchdog.py",
        "signal_parser": "signal parser.py",
        "Verifier": "verifier",
    }

    for name, config in AGENTS.items():
        log(f"Checking {name}...")
        process = check_process(process_patterns.get(name, name.lower()))
        log_tail = read_log_tail(config["log"])
        agent_states[name] = {
            "process": process,
            "log_tail": log_tail,
        }
        status = "ALIVE" if process["alive"] else "DEAD"
        log(f"  {name}: {status}")

    # Write memory file
    memory_content = build_memory(agent_states, now)
    MEMORY_FILE.write_text(memory_content)
    log(f"Memory file written: {MEMORY_FILE}")

    # Send Telegram report
    report = build_telegram_report(agent_states, now)
    telegram(report)
    log("Telegram report sent")

    # Also write a JSON state for programmatic access
    state_json = pathlib.Path.home() / "agent_state.json"
    state_data = {
        "updated": now.isoformat(),
        "agents": {
            name: {
                "alive": s["process"]["alive"],
                "pid": s["process"]["pid"],
            }
            for name, s in agent_states.items()
        }
    }
    state_json.write_text(json.dumps(state_data, indent=2))
    log(f"State JSON written: {state_json}")
    log("Memory Sync complete")

if __name__ == "__main__":
    main()
